global:
  scrape_interval: 1s  # Fréquence des scrapes (chaque 5 secondes)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Scrape de Prometheus lui-même

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['YOUR_IPv4:9100']  # Scrape de node_exporter no localhost or 127
